[2024-06-20T07:21:36.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:21:36.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:16:24.217978+00:00 [queued]>
[2024-06-20T07:21:36.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:16:24.217978+00:00 [queued]>
[2024-06-20T07:21:36.285+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T07:21:36.327+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_test_data> on 2024-06-20 07:16:24.217978+00:00
[2024-06-20T07:21:36.342+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T07:21:36.345+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-06-20T07:21:36.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'preprocess_test_data', 'manual__2024-06-20T07:16:24.217978+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpqmaqxbk2']
[2024-06-20T07:21:36.347+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask preprocess_test_data
[2024-06-20T07:21:36.478+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:16:24.217978+00:00 [running]> on host d509ebf65d45
[2024-06-20T07:21:36.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_test_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:16:24.217978+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:16:24.217978+00:00'
[2024-06-20T07:21:36.801+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:21:36.846+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:21:36.848+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 162, in preprocess_test_data
    data = process_data(data)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 34, in process_data
    numerical = process_numerical_df(numerical)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 52, in process_numerical_df
    import sklearn.preprocessing as preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2024-06-20T07:21:36.899+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=preprocess_test_data, run_id=manual__2024-06-20T07:16:24.217978+00:00, execution_date=20240620T071624, start_date=20240620T072136, end_date=20240620T072136
[2024-06-20T07:21:36.952+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task preprocess_test_data (No module named 'sklearn'; 65)
[2024-06-20T07:21:37.007+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:21:37.085+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:21:37.090+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
