[2024-06-20T07:43:13.073+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:43:13.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_train_data manual__2024-06-20T07:38:01.266138+00:00 [queued]>
[2024-06-20T07:43:13.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_train_data manual__2024-06-20T07:38:01.266138+00:00 [queued]>
[2024-06-20T07:43:13.103+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T07:43:13.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_train_data> on 2024-06-20 07:38:01.266138+00:00
[2024-06-20T07:43:13.122+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T07:43:13.123+0000] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2024-06-20T07:43:13.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'preprocess_train_data', 'manual__2024-06-20T07:38:01.266138+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpozi2f07r']
[2024-06-20T07:43:13.125+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask preprocess_train_data
[2024-06-20T07:43:13.169+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.preprocess_train_data manual__2024-06-20T07:38:01.266138+00:00 [running]> on host 223f65580fa9
[2024-06-20T07:43:13.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_train_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:38:01.266138+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:38:01.266138+00:00'
[2024-06-20T07:43:13.252+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:43:13.267+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:43:13.267+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 154, in preprocess_train_data
    data = process_data(data)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 34, in process_data
    numerical = process_numerical_df(numerical)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 52, in process_numerical_df
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-06-20T07:43:13.280+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=preprocess_train_data, run_id=manual__2024-06-20T07:38:01.266138+00:00, execution_date=20240620T073801, start_date=20240620T074313, end_date=20240620T074313
[2024-06-20T07:43:13.302+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task preprocess_train_data (No module named 'matplotlib'; 171)
[2024-06-20T07:43:13.339+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:43:13.356+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:43:13.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
