[2024-06-18T07:00:47.784+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:00:47.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-18T07:00:47.792+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:00:47.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:00:54.603+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:00:54.602+0000] {process_utils.py:263} INFO - Waiting up to 5 seconds for processes to exit...
[2024-06-18T07:01:33.036+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:01:33.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-18T07:01:33.040+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:01:33.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:01:34.191+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:01:34.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-18T07:01:34.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:01:34.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.231 seconds
[2024-06-18T07:02:04.679+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:02:04.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-18T07:02:04.683+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:02:04.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:02:05.995+0000] {logging_mixin.py:188} INFO - [2024-06-18T07:02:05.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-18T07:02:06.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-18T07:02:06.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.387 seconds
